apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dotnet-api-demo
  description: ASP.NET Core Demo API
spec:
  type: openapi
  lifecycle: experimental
  owner: user:kishore
  definition:
    $text: http://localhost:5175/swagger/v1/swagger.json
